apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}-svc
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}
