replicaCount: 2

namespace: sre-cource-student-84

image:
  repository: ghcr.io/ldest/sre-course/api
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: pustovetov.mts.tld
      paths:
        - path: /
          pathType: "Prefix"
          backend:
            service:
              name: api-svc
              port:
                number: 80

  tls: []

resources:
  limits:
    cpu: 250m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 32Mi

# Additional volumes on the output Deployment definition.
volumes:
  - name: config
    configMap:
      name: api-config
      items:
        - key: appsettings
          path: appsettings.json

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - mountPath: /app/appsettings.json
    name: config
    subPath: appsettings.json

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: DOTNET_ENVIRONMENT
    value: Development

config:
  dbhost: "91.185.86.221"
  dbport: "5000"
  dbname: "weather"
  dbuser: "postgres"
  dbpass: "oog7Zeikei6r"
